title: 래웅의 블로그
author: wlroh
email: wlroh.paul@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  래웅의 블로그, 공부한 내용을 기록하거나 일상 고민들을 적는 일기장이에요.
show_excerpts: true # set to true to show excerpts on the homepage
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this

collections:
  memoirs:
    output: true
sass:
  sass_dir: _sass
plainwhite:
  name: 래웅의 블로그
  tagline: Backend Developer
  intro: |
    목표를 위해 시스템을,

    시스템을 위해 회고를
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  analytics_id: G-HCKCGPDD5F
  dark_mode: true
  portfolio_image: "assets/images/portfolio.png"
  html_lang: "KR"
  condensed_mobile:
    - page
    - post
    - category_archive
  # generate social links in footer
  social_links:
    #twitter: samarsault
    github: wlroh
    linkedIn: in/wlroh
    #instagram: jekyll
    #facebook: jekyll
    #gitlab: jekyll
    email: wlroh.paul@gmail.com

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
  navigation:
    - title: Resume
      url: "/resume"
    - title: Posts
      url: "/"
    - title: Categories
      url: "/categories"
    - title: Memoirs
      url: "/memoirs"

# --------------------------------------  Resume Config  --------------------------------------

# Site
repository: wlroh/wlroh.github.io

# Content configuration version
version: 2

# Personal info
resume_name: 노웅래
resume_title: Backend Developer
resume_email: wlroh.paul@gmail.com
website: https://wlroh.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username: wlroh
#facebook_username: jekyll
linkedin_username: wlroh
#googlescholar_username: D847cGsAAAAJ

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-HCKCGPDD5F"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: assets/images/paul1.jpeg
about_content: |
  > 생산성을 높여, 더 큰 가치를 만듭니다.

  단순한 자동화를 넘어, 팀이 핵심 업무에 집중할 수 있는 환경을 만들기 위해 노력합니다. 반복적이고 비효율적인 업무를 발견하고, 문제 원인을 분석해 시스템화합니다. 이를 통해 팀의 업무 시간을 절감하고, 조직 전체의 업무 흐름을 개선해왔습니다.
  <br/><br/>
  > 꾸준히 배우며 더 나은 해결책을 찾습니다.
  
  프로그래밍은 정답이 없고 트레이드오프의 연속이라고 생각합니다. 다양한 스킬셋의 장단점을 깊이 이해하며, 상황에 맞는 최적의 해결책을 찾는 데 집중합니다. 이러한 노력은 더 나은 아키텍처 설계와 합리적인 기술 선택으로 이어진다고 믿습니다.
  <br/><br/>
  > 지식을 나누며 함께 성장합니다.
  
  배운 지식을 나누는 것은 단순한 공유를 넘어, 팀과 조직의 발전에 기여하는 길이라고 생각합니다. 사내 스터디와 발표를 통해 새로운 기술과 인사이트를 함께 탐구해왔습니다.

# -------------------------------------- END Resume Config  --------------------------------------

# Build settings
remote_theme: samarsault/plainwhite-jekyll
# theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
